drop database Grocery_store;
Create database Grocery_store;
use Grocery_store;
create table Supplier(
Sup_id tinyint primary key,
Sup_name varchar(250),
address text);

create table categories(
cat_id tinyint primary key,
cat_name varchar(250));

create table employees(
emp_id tinyint primary key,
emp_name varchar(250),
hire_date varchar(250));

create table customers(
cust_id smallint primary key,
cust_name varchar(250),
address Text);

create table products(
prod_id tinyint primary key,
prod_name varchar(250),
sup_id tinyint,
cat_id tinyint,
price decimal(10,2),
foreign key (sup_id) references supplier(sup_id)
on update cascade on delete cascade,
foreign key (cat_id) references categories(cat_id)
on update cascade on delete cascade);

create table orders(
ord_id smallint primary key,
cust_id smallint,
emp_id tinyint,
order_date varchar(250),
foreign key(cust_id) references customers(cust_id)
on update cascade on delete cascade,
foreign key (emp_id) references employees(emp_id)
on update cascade on delete cascade);

CREATE TABLE IF NOT EXISTS order_details (
ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
ord_id SMALLINT,
prod_id TINYINT,
quantity TINYINT,
each_price DECIMAL(10,2),
total_price DECIMAL(10,2),
FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (prod_id) REFERENCES products(prod_id)
ON UPDATE CASCADE ON DELETE CASCADE);

select * from order_details;

-- customer insights
-- number of unique customers have placed orders
SELECT COUNT(DISTINCT cust_id) 
FROM orders;

-- The customer who placed the highest number of orders
SELECT c.cust_name, COUNT(o.ord_id) AS total_orders
FROM orders AS o
JOIN customers AS c ON o.cust_id = c.cust_id
GROUP BY c.cust_name
ORDER BY total_orders DESC;

-- The total and average purchase value per customer
select max(total_price) from order_details;
select  c.cust_name,c.cust_id,sum(total_price) as Total_Purchase,avg(total_price) as Average_purchase
from order_details od 
join orders o on od.ord_id=o.ord_id
join customers AS c ON o.cust_id = c.cust_id
group by o.cust_id
order by Total_purchase desc;

-- The top 5 customers by total purchase amount
select c.cust_name,sum(od.total_price) as total_purchase
from order_details od
join orders o on od.ord_id=o.ord_id
join customers as c on o.cust_id=c.cust_id
group by o.cust_id
order by Total_purchase desc
limit 5;

-- Ranks customers based on their total purchase amount
WITH CustomerSpending AS (
SELECT c.cust_name,SUM(od.total_price) AS total_spent
FROM customers c JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY o.cust_id)
SELECT cust_name,total_spent,
DENSE_RANK() OVER (ORDER BY total_spent DESC) AS customer_rank
FROM CustomerSpending;

-- Finds customers who have not made a purchase in the last 180 days
select c.cust_id,c.cust_name, MAX(o.order_date) as last_order_date,
    DATEDIFF(CURDATE(), MAX(o.order_date)) as days_since_last_order
from customers c join orders o on c.cust_id = o.cust_id
group by c.cust_id, c.cust_name
having days_since_last_order > 180
order by days_since_last_order DESC;


-- Product Performance
-- How many products exist in each category.
select * from products;
select cat_name,count(prod_id)
from categories c
join products p on c.cat_id=p.cat_id
group by p.cat_id;

-- What is the average price of products by category?
select * from order_details;
select cat_name,avg(p.price)
from products p 
join categories c on p.cat_id=c.cat_id
group by p.cat_id;

-- The product that have the highest total sales volume (by quantity)
select prod_name,sum(od.quantity) as Total_sales
from order_details od
join products p on od.prod_id=p.prod_id
group by p.prod_id
order by Total_sales desc
limit 1;

-- What is the total revenue generated by each product?
select prod_name,sum(od.total_price) as Total_revenue
from order_details od
join products p on od.prod_id=p.prod_id
group by od.prod_id
order by Total_revenue desc;

-- How the product sales vary by category and supplier (quantity).
select * from supplier;
select c.cat_name,s.sup_name,sum(od.quantity) as Product_sales
from order_details od 
join products p on p.prod_id=od.prod_id
join categories c on p.cat_id=c.cat_id
join supplier s on s.sup_id=p.sup_id
group by c.cat_name,s.sup_name
order by c.cat_name,product_sales desc;

-- Identifies the best-selling product within each category based on total revenue
with ProductSales as (select c.cat_name,p.prod_name,
sum(od.total_price) as total_revenue,
row_number() over(partition by c.cat_name order by sum(od.total_price) desc) as rn
from order_details od 
join products p on od.prod_id = p.prod_id
join categories c on p.cat_id = c.cat_id
group by c.cat_name, p.prod_name)
select cat_name,prod_name,total_revenue
from ProductSales where rn = 1
order by total_revenue desc;

-- Sales and Order Trends
-- How many orders have been placed in total
select count(ord_id) 
from orders;

-- What is the average value per order
select ord_id,avg(total_price)
 from order_details
 group by ord_id;
    
-- On which dates were the most orders placed?
select order_date,count(ord_id) as orders_placed 
from orders
group by order_date
order by orders_placed desc
limit 1;

-- What are the monthly trends in order volume and revenue
select * from orders;
UPDATE orders
SET order_date = STR_TO_DATE(order_date, '%m/%d/%Y');
ALTER TABLE orders MODIFY order_date DATE;
select YEAR(o.order_date) AS order_year,
    MONTH(o.order_date) AS order_month,
    count(distinct o.ord_id) as Total_orders,
    sum(od.total_price) as Total_revenue 
from order_details od 
join orders o on o.ord_id=od.ord_id
group by order_year,order_month 
ORDER BY order_year,order_month;


-- How do order patterns vary across weekdays and weekends?
select * from orders;
SELECT count(o.ord_id) as Total_Orders,avg(o.ord_id) as average_orders,sum(total_price) as Total_revenue,
avg(total_price) as Average_revenue,
CASE
	WHEN WEEKDAY(order_date) IN (5, 6) THEN 'Weekend'
	ELSE 'Weekday'
END AS day_type
FROM orders o
join order_details od on o.ord_id=od.ord_id
group by day_type;

-- Supplier Contribution
-- How many suppliers are there in the database
select count(*) from supplier;

-- The supplier provides the most products
select s.sup_id,s.sup_name,count(*) as Products_provided
from supplier s
join products p on s.sup_id=p.sup_id
group by p.sup_id
order by products_provided desc;

-- What is the average price of products from each supplier?
select s.sup_id,sup_name,avg(price) as avg_price
from products p
join supplier s on p.sup_id=s.sup_id
group by p.sup_id
order by avg_price desc;

-- Which suppliers contribute the most to total product sales (by revenue)?
select s.sup_id,s.sup_name,sum(total_price) as total_revenue
from order_details od
join products p on od.prod_id=p.prod_id
join supplier s on p.sup_id=s.sup_id
group by p.sup_id
order by total_revenue desc;


-- Which suppliers contribute the most of sales of a specific category (by revenue)?
WITH RankedSuppliers AS (
    SELECT s.sup_name,c.cat_name,
        SUM(od.total_price) AS TotalRevenue,
        ROW_NUMBER() OVER(PARTITION BY c.cat_name ORDER BY SUM(od.total_price) DESC) as rank_num
    FROM Order_Details od
	JOIN Products p ON od.prod_id = p.prod_id
    JOIN Supplier s ON p.sup_id = s.sup_id
    JOIN Categories c ON p.cat_id = c.cat_id
    GROUP BY c.cat_name, s.sup_name)
SELECT sup_name,cat_name,TotalRevenue
FROM RankedSuppliers
WHERE rank_num = 1;

-- Employee Performance
-- How many employees have processed orders?
select * from orders;
select count(distinct emp_id) as Total_emp_proc_ord
from orders;

-- Which employees have handled the most orders?
select e.emp_id,e.emp_name,count(*) as orders_processed
from orders o 
join employees e on o.emp_id=e.emp_id
group by emp_id
order by orders_processed desc;

-- What is the total sales value processed by each employee?
select o.emp_id,emp_name,sum(total_price) as Sales_proc
from order_details od
join orders o on od.ord_id=o.ord_id 
join employees e on o.emp_id=e.emp_id
group by o.emp_id
order by Sales_proc desc; 

-- What is the average order value handled per employee?
select e.emp_id,e.emp_name,avg(total_price) as Avg_value
from order_details od
join orders o on od.ord_id=o.ord_id
join employees e on o.emp_id=e.emp_id
group by o.emp_id
order by avg_value desc;

-- Order Details Deep Dive
-- What is the relationship between quantity ordered and total price?
select * from order_details;
SELECT prod_id,quantity,each_price,total_price
FROM order_details;

-- What is the average quantity ordered per product?
select p.prod_id,p.prod_name,avg(quantity) as Avg_Quan
from order_details od
join products p on p.prod_id=od.prod_id 
group by od.prod_id
order by avg_Quan desc;

-- How does the unit price vary across products and orders?
select od.prod_id,prod_name,od.ord_id,MIN(od.each_price) AS min_unit_price,
    MAX(od.each_price) AS max_unit_price 
from order_details od
join products p on od.prod_id=p.prod_id
group by prod_id,ord_id
order by prod_name,ord_id;

-- Products Most Frequently Purchased in Bulk
select p.prod_name,count(od.ord_detid) as number_of_bulk_purchases
from order_details od
join products p on od.prod_id = p.prod_id
where od.quantity >= 5 -- define a 'bulk' purchase as 5 or more items
group by p.prod_name
order by number_of_bulk_purchases desc;

